# Generated by Django 6.0.6 on 2026-06-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_api", models.PositiveIntegerField(db_index=True, unique=True)),
                ("season", models.CharField(blank=True, default="", max_length=20)),
                ("matchday", models.PositiveIntegerField(blank=True, null=True)),
                ("stage", models.CharField(blank=True, default="", max_length=50)),
                (
                    "round",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ronda/jornada de API-Football (league.round).",
                        max_length=50,
                    ),
                ),
                ("group", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("TIMED", "Timed"),
                            ("IN_PLAY", "En juego"),
                            ("PAUSED", "Pausado"),
                            ("FINISHED", "Finalizado"),
                            ("SUSPENDED", "Suspendido"),
                            ("POSTPONED", "Aplazado"),
                            ("CANCELLED", "Cancelado"),
                            ("AWARDED", "Adjudicado"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("utc_date", models.DateTimeField()),
                ("home_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("away_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("elo_processed", models.BooleanField(default=False)),
                ("home_elo_before", models.FloatField(blank=True, null=True)),
                ("away_elo_before", models.FloatField(blank=True, null=True)),
                ("home_elo_after", models.FloatField(blank=True, null=True)),
                ("away_elo_after", models.FloatField(blank=True, null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="teams.competition",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ["-utc_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "utc_date"],
                        name="matches_mat_status_6e44da_idx",
                    ),
                    models.Index(
                        fields=["elo_processed"], name="matches_mat_elo_pro_9bc0f0_idx"
                    ),
                    models.Index(
                        fields=["competition", "season"],
                        name="matches_mat_competi_e55045_idx",
                    ),
                ],
            },
        ),
    ]
