# Generated by Django 6.0.6 on 2026-07-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_api", models.PositiveIntegerField(db_index=True, unique=True)),
                ("season", models.CharField(blank=True, default="", max_length=20)),
                (
                    "round",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ronda/jornada legible (derivada de stage/group/matchday).",
                        max_length=50,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=50)),
                ("group", models.CharField(blank=True, default="", max_length=50)),
                ("matchday", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programado"),
                            ("TIMED", "Timed"),
                            ("IN_PLAY", "En juego"),
                            ("PAUSED", "Pausado"),
                            ("FINISHED", "Finalizado"),
                            ("SUSPENDED", "Suspendido"),
                            ("POSTPONED", "Aplazado"),
                            ("CANCELLED", "Cancelado"),
                            ("AWARDED", "Adjudicado"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "status_short",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Status corto derivado de score.duration (FT, AET, PEN).",
                        max_length=10,
                    ),
                ),
                ("utc_date", models.DateTimeField()),
                (
                    "is_neutral",
                    models.BooleanField(
                        default=False,
                        help_text="Sede neutral: la localía no aplica en Elo.",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Estadio donde se disputa el partido (por partido).",
                        max_length=200,
                    ),
                ),
                (
                    "referee",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Árbitro del partido.",
                        max_length=200,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("FRIENDLY", "Amistoso"),
                            ("LEAGUE", "Liga"),
                            ("CUP", "Copa"),
                            ("KNOCKOUT", "Eliminatoria"),
                            ("INTERNATIONAL", "Internacional"),
                        ],
                        default="LEAGUE",
                        max_length=20,
                    ),
                ),
                (
                    "rest_days_home",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rest_days_away",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("home_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("away_goals", models.PositiveIntegerField(blank=True, null=True)),
                ("elo_processed", models.BooleanField(default=False)),
                ("home_elo_before", models.FloatField(blank=True, null=True)),
                ("away_elo_before", models.FloatField(blank=True, null=True)),
                ("home_elo_after", models.FloatField(blank=True, null=True)),
                ("away_elo_after", models.FloatField(blank=True, null=True)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="teams.competition",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ["-utc_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "utc_date"],
                        name="matches_mat_status_6e44da_idx",
                    ),
                    models.Index(
                        fields=["elo_processed"], name="matches_mat_elo_pro_9bc0f0_idx"
                    ),
                    models.Index(
                        fields=["competition", "season"],
                        name="matches_mat_competi_e55045_idx",
                    ),
                ],
            },
        ),
    ]
