# Generated by Django 6.0.6 on 2026-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="group",
        ),
        migrations.RemoveField(
            model_name="match",
            name="matchday",
        ),
        migrations.RemoveField(
            model_name="match",
            name="stage",
        ),
        migrations.AddField(
            model_name="match",
            name="status_short",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Status corto de API-Football (FT, AET, PEN, ...).",
                max_length=10,
            ),
        ),
    ]
