# Generated by Django 6.0.6 on 2026-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_remove_match_group_remove_match_matchday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="importance",
            field=models.CharField(
                choices=[
                    ("FRIENDLY", "Amistoso"),
                    ("LEAGUE", "Liga"),
                    ("CUP", "Copa"),
                    ("KNOCKOUT", "Eliminatoria"),
                    ("INTERNATIONAL", "Internacional"),
                ],
                default="LEAGUE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="is_neutral",
            field=models.BooleanField(
                default=False, help_text="Sede neutral: la localía no aplica en Elo."
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="referee",
            field=models.CharField(
                blank=True, default="", help_text="Árbitro del partido.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="rest_days_away",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="rest_days_home",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="venue",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Estadio donde se disputa el partido (por partido).",
                max_length=200,
            ),
        ),
    ]
