# Generated by Django 6.0.6 on 2026-07-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_api", models.PositiveIntegerField(db_index=True, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("area_name", models.CharField(blank=True, default="", max_length=100)),
                ("area_code", models.CharField(blank=True, default="", max_length=20)),
                (
                    "league_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tipo de competición (league/cup).",
                        max_length=20,
                    ),
                ),
                ("logo", models.URLField(blank=True, default="")),
                (
                    "current_season",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("plan", models.CharField(blank=True, default="", max_length=20)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LEAGUE", "Liga"),
                            ("CUP", "Copa nacional"),
                            ("CONTINENTAL", "Copa continental"),
                            ("INTERNATIONAL", "Torneo de selecciones"),
                            ("WORLD_CUP", "Mundial"),
                            ("QUALIFIERS", "Eliminatorias"),
                            ("FRIENDLY", "Amistoso"),
                            ("OTHER", "Otra"),
                        ],
                        default="LEAGUE",
                        max_length=20,
                    ),
                ),
                ("home_advantage", models.PositiveSmallIntegerField(default=80)),
            ],
            options={
                "verbose_name": "Competición",
                "verbose_name_plural": "Competiciones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_api", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("tla", models.CharField(blank=True, default="", max_length=10)),
                ("crest_url", models.URLField(blank=True, default="")),
                ("founded", models.PositiveIntegerField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=200)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "club_colors",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("elo", models.FloatField(default=1500.0)),
                ("matches_played", models.PositiveIntegerField(default=0)),
                (
                    "last_regressed_season",
                    models.CharField(blank=True, default="", max_length=20),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=20)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_links",
                        to="teams.competition",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_links",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo-Competición",
                "verbose_name_plural": "Equipos-Competiciones",
                "unique_together": {("team", "competition", "season")},
            },
        ),
    ]
