# Generated by Django 6.0.6 on 2026-06-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="short_name",
        ),
    ]
