# Generated by Django 6.0.6 on 2026-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="source",
            field=models.CharField(
                choices=[
                    ("footballdata", "football-data.org"),
                    ("apifootball", "API-Football"),
                ],
                default="footballdata",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="source",
            field=models.CharField(
                choices=[
                    ("footballdata", "football-data.org"),
                    ("apifootball", "API-Football"),
                ],
                default="footballdata",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="id_api",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="id_api",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="competition",
            unique_together={("id_api", "source")},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("id_api", "source")},
        ),
    ]
