# Generated by Django 6.0.6 on 2026-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_remove_team_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="home_advantage",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="competition",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LEAGUE", "Liga"),
                    ("CUP", "Copa nacional"),
                    ("CONTINENTAL", "Copa continental"),
                    ("WORLD_CUP", "Mundial"),
                    ("QUALIFIERS", "Eliminatorias"),
                    ("FRIENDLY", "Amistoso"),
                    ("OTHER", "Otra"),
                ],
                default="LEAGUE",
                max_length=20,
            ),
        ),
    ]
