# Generated by Django 6.0.6 on 2026-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_competition_home_advantage_competition_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="last_regressed_season",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
