# Generated by Django 6.0.6 on 2026-06-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_team_last_regressed_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LEAGUE", "Liga"),
                    ("CUP", "Copa nacional"),
                    ("CONTINENTAL", "Copa continental"),
                    ("INTERNATIONAL", "Torneo de selecciones"),
                    ("WORLD_CUP", "Mundial"),
                    ("QUALIFIERS", "Eliminatorias"),
                    ("FRIENDLY", "Amistoso"),
                    ("OTHER", "Otra"),
                ],
                default="LEAGUE",
                max_length=20,
            ),
        ),
    ]
