# Generated by Django 6.0.6 on 2026-07-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("1X2_HOME", "Local (1X2)"),
                            ("1X2_DRAW", "Empate (1X2)"),
                            ("1X2_AWAY", "Visitante (1X2)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bin_start", models.FloatField()),
                ("bin_end", models.FloatField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "predicted_avg",
                    models.FloatField(
                        default=0.0,
                        help_text="Promedio de probabilidad pronosticada en el bin.",
                    ),
                ),
                (
                    "observed_freq",
                    models.FloatField(
                        default=0.0,
                        help_text="Fracción real que ocurrió en el bin (0..1).",
                    ),
                ),
                ("window_from", models.DateTimeField(blank=True, null=True)),
                ("window_to", models.DateTimeField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bin de calibración",
                "verbose_name_plural": "Bins de calibración",
                "ordering": ["market", "bin_start"],
                "unique_together": {
                    ("market", "bin_start", "bin_end", "window_from", "window_to")
                },
            },
        ),
        migrations.CreateModel(
            name="ForecastEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_home_goals", models.PositiveSmallIntegerField()),
                ("actual_away_goals", models.PositiveSmallIntegerField()),
                (
                    "actual_outcome",
                    models.CharField(
                        help_text="1 (local), X (empate) o 2 (visitante). PEN cuenta como empate.",
                        max_length=1,
                    ),
                ),
                ("log_loss_1x2", models.FloatField()),
                ("brier_1x2", models.FloatField()),
                ("rps_1x2", models.FloatField()),
                ("ae_xg_home", models.FloatField()),
                ("ae_xg_away", models.FloatField()),
                (
                    "ae_total",
                    models.FloatField(help_text="|xg_home + xg_away − goles_totales|."),
                ),
                ("top_score_hit", models.BooleanField(default=False)),
                (
                    "season",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="True si el Forecast evaluado era fallback solo Elo.",
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecast_evaluations",
                        to="teams.competition",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["-match__utc_date"],
                "indexes": [
                    models.Index(
                        fields=["season"], name="validation__season_90bb42_idx"
                    ),
                    models.Index(
                        fields=["competition", "season"],
                        name="validation__competi_45aeea_idx",
                    ),
                ],
            },
        ),
    ]
