# Generated by Django 6.0.6 on 2026-07-20 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Avg, Count, Sum


def backfill_legacy_snapshot(apps, schema_editor):
    """Convierte los CalibrationBin existentes (single snapshot vigente
    bajo el modelo anterior) en un CalibrationSnapshot LEGACY.

    Agrupa los bins por (window_from, window_to) — típicamente un único
    grupo, ya que el código viejo hacía `delete()` antes de insertar —
    y crea un snapshot por grupo con KPIs agregados sobre las
    ForecastEvaluation del rango. Asigna el FK snapshot a los bins.

    Idempotente: si ya existen snapshots (re-migración), no hace nada.
    """
    CalibrationSnapshot = apps.get_model("validation", "CalibrationSnapshot")
    CalibrationBin = apps.get_model("validation", "CalibrationBin")
    ForecastEvaluation = apps.get_model("validation", "ForecastEvaluation")

    if CalibrationSnapshot.objects.exists():
        # Ya migrado (re-ejecución): nada que hacer.
        return

    if not CalibrationBin.objects.exists():
        # Sin calibración previa: nada que migrar. El sentinel del
        # daily_update gestiona el primer snapshot desde cero.
        return

    # Lee los bins directamente (los campos legacy todavía existen en
    # este punto de la migración: window_from/window_to/snapshot_at).
    bins = list(
        CalibrationBin.objects.values(
            "id",
            "market",
            "bin_start",
            "bin_end",
            "count",
            "predicted_avg",
            "observed_freq",
            "window_from",
            "window_to",
            "snapshot_at",
        )
    )

    # Agrupa por ventana (todos los bins del mismo snapshot comparten
    # window_from/window_to en el modelo viejo).
    groups = {}
    for b in bins:
        key = (b["window_from"], b["window_to"])
        groups.setdefault(key, []).append(b)

    for (w_from, w_to), group_bins in groups.items():
        snap_at = max(b["snapshot_at"] for b in group_bins)
        n = sum(b["count"] for b in group_bins)

        # KPIs sobre evaluaciones del rango de la ventana. Si los bins
        # existían pero las evaluaciones se borraron, dejamos KPIs en 0.
        kpis = {
            "log_loss_1x2": 0.0,
            "brier_1x2": 0.0,
            "rps_1x2": 0.0,
            "ae_xg_home": 0.0,
            "ae_xg_away": 0.0,
            "ae_total": 0.0,
            "top_score_hit_ratio": 0.0,
        }
        eval_qs = ForecastEvaluation.objects.all()
        if w_from is not None:
            eval_qs = eval_qs.filter(match__utc_date__gte=w_from)
        if w_to is not None:
            eval_qs = eval_qs.filter(match__utc_date__lte=w_to)
        if eval_qs.exists():
            agg = eval_qs.aggregate(
                avg_ll=Avg("log_loss_1x2"),
                avg_brier=Avg("brier_1x2"),
                avg_rps=Avg("rps_1x2"),
                avg_ae_home=Avg("ae_xg_home"),
                avg_ae_away=Avg("ae_xg_away"),
                avg_ae_total=Avg("ae_total"),
                hits=Sum("top_score_hit"),
                total=Count("id"),
            )
            kpis = {
                "log_loss_1x2": agg["avg_ll"] or 0.0,
                "brier_1x2": agg["avg_brier"] or 0.0,
                "rps_1x2": agg["avg_rps"] or 0.0,
                "ae_xg_home": agg["avg_ae_home"] or 0.0,
                "ae_xg_away": agg["avg_ae_away"] or 0.0,
                "ae_total": agg["avg_ae_total"] or 0.0,
                "top_score_hit_ratio": (agg["hits"] or 0) / (agg["total"] or 1),
            }

        snapshot = CalibrationSnapshot.objects.create(
            snapshot_at=snap_at,
            window_from=w_from,
            window_to=w_to,
            n=n,
            trigger="legacy",
            **kpis,
        )
        ids = [b["id"] for b in group_bins]
        CalibrationBin.objects.filter(id__in=ids).update(snapshot=snapshot)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("window_from", models.DateTimeField(blank=True, null=True)),
                ("window_to", models.DateTimeField(blank=True, null=True)),
                ("n", models.PositiveIntegerField(default=0)),
                ("log_loss_1x2", models.FloatField(default=0.0)),
                ("brier_1x2", models.FloatField(default=0.0)),
                ("rps_1x2", models.FloatField(default=0.0)),
                ("ae_xg_home", models.FloatField(default=0.0)),
                ("ae_xg_away", models.FloatField(default=0.0)),
                ("ae_total", models.FloatField(default=0.0)),
                ("top_score_hit_ratio", models.FloatField(default=0.0)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (evaluate_forecasts)"),
                            ("rebuild", "Rebuild (--rebuild)"),
                            ("daily", "Daily update"),
                            ("force", "Force (--force-calibration)"),
                            ("legacy", "Legacy (migración)"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("season", models.CharField(blank=True, default="", max_length=20)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibration_snapshots",
                        to="teams.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de calibración",
                "verbose_name_plural": "Snapshots de calibración",
                "ordering": ["-snapshot_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="calibrationbin",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="calibrationbin",
            name="snapshot",
            field=models.ForeignKey(
                help_text="Snapshot al que pertenece el bin. Null solo durante migraciones.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bins",
                to="validation.calibrationsnapshot",
            ),
        ),
        migrations.RunPython(
            backfill_legacy_snapshot,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="calibrationbin",
            unique_together={("snapshot", "market", "bin_start")},
        ),
        migrations.AddIndex(
            model_name="calibrationsnapshot",
            index=models.Index(
                fields=["snapshot_at"], name="validation__snapsho_ab75c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calibrationsnapshot",
            index=models.Index(
                fields=["season", "competition"], name="validation__season_cda93b_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="calibrationbin",
            name="snapshot_at",
        ),
        migrations.RemoveField(
            model_name="calibrationbin",
            name="window_from",
        ),
        migrations.RemoveField(
            model_name="calibrationbin",
            name="window_to",
        ),
    ]
