# Generated by Django 6.0.6 on 2026-06-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0003_match_importance_match_is_neutral_match_referee_and_more"),
        ("teams", "0003_competition_home_advantage_competition_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_home", models.BooleanField(default=False)),
                (
                    "goals_first_half",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "goals_second_half",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "shots_total",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "shots_on_goal",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "shots_off_goal",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "shots_blocked",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "shots_inside_box",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "shots_outside_box",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("possession", models.FloatField(blank=True, null=True)),
                ("corners", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("offsides", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "fouls_committed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "yellow_cards",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("red_cards", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "goalkeeper_saves",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("passes_total", models.PositiveIntegerField(blank=True, null=True)),
                ("passes_accurate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="matches.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_statistics",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de partido",
                "verbose_name_plural": "Estadísticas de partidos",
                "ordering": ["-match__utc_date"],
                "unique_together": {("match", "team")},
            },
        ),
    ]
