# Generated by Django 6.0.6 on 2026-06-29 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_match_importance_match_is_neutral_match_referee_and_more"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchstatistics",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="matches.match",
            ),
        ),
    ]
