"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=".secret")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-+cu@_5o!b42y7pvtf(uwm+5b733946@#=on)3k(cd%j75tdd$z",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "teams",
    "matches",
    "elo",
    "forecasts",
    "api_client",
    "validation",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-ni"

TIME_ZONE = "America/Managua"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# football-data.org (v4) — única fuente de datos.
#
# Competiciones de clubes y selecciones. La capa Free cubre solo 12
# competiciones (FOOTBALL_DATA_FREE_COMPETITION_CODES); las demás
# devuelven 403. La cobertura se descubre vía /v4/competitions y se
# filtra a las del plan Free (ver comando sync_competitions). Elo
# inicial: ELO_DEFAULT (1500) para equipos nuevos en ligas sin
# LeagueStrength; se recalibra con recompute_league_strength tras el
# backfill.
#
# Plan Free: 10 req/min, sin límite diario explícito, solo marcadores
# /fixtures/schedules/league tables (sin bookings, alineaciones ni
# estadísticas agregadas). Los partidos históricos se piden vía
# /v4/competitions/{id}/matches?season=YYYY, pero el Free solo expone las
# últimas ~3-4 temporadas de cada competición (las anteriores devuelven
# 403); ver docs/api_football.md §Ventana histórica real del plan Free.
# Los valores de rate-limit/budget son conservadores para
# no quemar el techo por minuto.
API_CACHE_TTL_MINUTES = 60
FOOTBALL_DATA_TOKEN = os.environ.get("FOOTBALL_DATA_TOKEN", "")
FOOTBALL_DATA_BASE_URL = "https://api.football-data.org"
# 10 req/min → ~6s entre peticiones para no tocar el techo.
FOOTBALL_DATA_RATE_LIMIT_SECONDS = 6.0
# Tope diario de seguridad (el plan Free no publica un daily budget,
# pero 10/min → 600/hora; 1000 deja margen prudente).
FOOTBALL_DATA_DAILY_BUDGET = 1000
# Códigos de competición accesibles en plan Free (ver coverage). El
# comando sync_competitions filtra /v4/competitions por este set.
FOOTBALL_DATA_FREE_COMPETITION_CODES = {
    "CL",  # UEFA Champions League
    "PL",  # Premier League
    "ELC",  # Championship
    "BL1",  # Bundesliga
    "FL1",  # Ligue 1
    "SA",  # Serie A
    "PD",  # La Liga
    "DED",  # Eredivisie
    "PPL",  # Primeira Liga
    "BSA",  # Campeonato Brasileiro Série A
    "WC",  # FIFA World Cup
    "EC",  # European Championship
}

# Elo inicial para nuevos equipos cuando no existe LeagueStrength.
# Equipos nuevos en ligas sin historial reciben ELO_DEFAULT (1500);
# tras backfill, recompute_league_strength recalibra con promedios reales.

# Elo system constants (see docs/elo.md)
ELO_DEFAULT = 1500
# Ventaja de localía por defecto (fallback cuando la competición no la
# define explícitamente). docs/elo.md: liga nacional 70-90, selecciones
# 50-80, Mundial/neutral 0. La localía real se toma de
# Competition.home_advantage; este valor solo se usa en cálculos
# manuales o si la competición no existe.
ELO_HOME_ADVANTAGE = 80
# Factor K por tipo de competición (docs/elo.md §Factor K).
#   Mundial 30, Eliminatorias 25, Primera división/Copas nacionales 20,
#   Amistosos 15. Equipos nuevos usan K=40 durante sus primeros
#   ELO_NEW_TEAM_MATCHES partidos, ignorando el kind.
ELO_K_DEFAULT = 20  # Clubes profesionales (ligas top)
ELO_K_WORLD_CUP = 30
ELO_K_QUALIFIERS = 25
ELO_K_CUP = 20
ELO_K_FRIENDLY = 15
ELO_K_CONTINENTAL = 25
ELO_K_NEW = 40
ELO_NEW_TEAM_MATCHES = 20

# Forecast system constants (see docs/pronostico.md, docs/xG.md)
# Forma reciente: dos ventanas (docs: Forma = 0.65·Forma20 + 0.35·Forma5).
FORECAST_FORM_SHORT = 5
FORECAST_FORM_LONG = 20
FORECAST_FORM_SHORT_WEIGHT = 0.35
FORECAST_FORM_LONG_WEIGHT = 0.65
# Ponderación temporal exp(-Dias/180) según docs/xG.md §Ponderación temporal.
FORECAST_DECAY_DAYS = 180
# Ataque/defensa separados por local/visitante: mínimo de partidos por
# condición para considerar el rating válido (si no, fallback Elo-only).
FORECAST_MIN_HISTORY = 5
FORECAST_MIN_VENUE_HISTORY = 3
# Clamp de goles esperados (docs/xG.md §Normalización): 0.20 ≤ λ ≤ 4.00.
FORECAST_LAMBDA_MIN = 0.20
FORECAST_LAMBDA_MAX = 4.00
# Factor Elo suave (no lineal). docs/xG.md §Corrección mediante Elo:
# "función suave que evite exagerar las diferencias". Usamos una tanh
# acotada: factor = 1 + gain·tanh(diff/scale). gain=0.5 limita el
# desplazamiento del λ a ±50% por Elo.
FORECAST_ELO_GAIN = 0.5
FORECAST_ELO_SCALE = 800.0
# Factor de forma multiplicativo sobre λ: ajuste leve (no dominante).
# docs/xG.md: "La forma complementa las estadísticas históricas, pero
# nunca las reemplaza." Limitamos el impacto a ±FORM_MAX_IMPACT.
FORECAST_FORM_MAX_IMPACT = 0.20
POISSON_MAX_GOALS = 5
# Corrección Dixon-Coles para baja anotación. rho negativo incrementa la
# probabilidad de 0-0 y 1-1 (Poisson independiente la subestima).
# Valor típico en fútbol: -0.13. 0.0 desactiva la corrección.
DIXON_COLES_RHO = -0.13
# Gol promedio histórico usado como base cuando un equipo no tiene
# historial suficiente (< FORECAST_MIN_HISTORY). El pronóstico fallback
# se basa solo en la diferencia Elo multiplicada por este baseline.
FORECAST_FALLBACK_BASELINE = 1.35
# Umbral de antigüedad (meses) para considerar la forma reciente de un
# equipo como "stale". Safety net (24m): protege ante resincronizaciones
# o equipos inactivos largos.
FORECAST_STALE_MONTHS = 24

# Ventana de sincronización y pronóstico.
# Solo se pronostican y sincronizan partidos programados dentro de esta
# ventana hacia adelante (pronóstico semanal). Los datos lejanos cambian
# (fechas, forma reciente, Elo) por lo que no tiene sentido pronosticarlos.
FORECAST_SCHEDULE_DAYS = 7
# Ventana hacia atrás para capturar resultados recién finalizados
# (incluye aplazamientos/retardos de actualización de la API).
SYNC_BACK_DAYS = 3

# Frecuencia de reconstrucción de la calibración dentro del orquestador
# diario (daily_update). Con 10k+ evaluaciones, añadir 5-10 partidos/día
# mueve los promedios por bin en <0.001: no aporta signal diario. 30 días
# equilibran frescura y coste (~30s por refresh). El orquestador usa
# CalibrationBin.snapshot_at como sentinel: si ocurre una calibración
# manual intermedia (--rebuild), el contador se reinicia automáticamente.
CALIBRATION_INTERVAL_DAYS = 30


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "alpha": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
