"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=".secret")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-+cu@_5o!b42y7pvtf(uwm+5b733946@#=on)3k(cd%j75tdd$z",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "teams",
    "matches",
    "elo",
    "forecasts",
    "api_client",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-ni"

TIME_ZONE = "America/Managua"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# API-Football (api-sports.io v3) — única fuente de datos.
#
# Competiciones de clubes, selecciones nacionales y amistosos. La
# cobertura se descubre dinámicamente vía /leagues (ver comando
# sync_competitions). API_FOOTBALL_LEAGUES es solo un catálogo semilla
# para calibrar el Elo inicial por liga; las ligas descubiertas que no
# estén listadas usan ELO_DEFAULT.
#
# Plan Free: 100 req/día, 10/min, solo temporadas 2022-2024, y date=
# restringido a hoy ± 1 día (ventana rolling de 3 días).
# Plan Pro: 7,500 req/día, 300/min, histórico profundo (~2008+) y
# temporada actual desbloqueada vía league+season y date= sin ventana.
# Los valores de rate-limit/budget están preparados para plan Pro.
API_CACHE_TTL_MINUTES = 60
API_FOOTBALL_KEY = os.environ.get("API_FOOTBALL_KEY", "")
API_FOOTBALL_BASE_URL = "https://v3.football.api-sports.io"
API_FOOTBALL_RATE_LIMIT_SECONDS = 0.25
API_FOOTBALL_DAILY_BUDGET = 7000

# Catálogo semilla de calibración Elo: (league_id, code, nombre, elo_inicial).
# code se almacena como Competition.code (el league_id como string).
# initial_elo se usa al crear LeagueStrength y al asignar Elo a equipos
# nuevos (ver docs/elo.md). Las ligas descubiertas no listadas aquí usan
# ELO_DEFAULT y se recalibran con recompute_league_strength tras el backfill.
API_FOOTBALL_LEAGUES = [
    # --- Ligas europeas top ---
    (39, "39", "Premier League", 1600),
    (140, "140", "La Liga", 1570),
    (78, "78", "Bundesliga", 1560),
    (135, "135", "Serie A", 1550),
    (61, "61", "Ligue 1", 1540),
    (88, "88", "Eredivisie", 1450),
    (94, "94", "Primeira Liga", 1450),
    # --- Sudamérica ---
    (13, "13", "Copa Libertadores", 1500),
    (11, "11", "Copa Sudamericana", 1450),
    (71, "71", "Brasileirão Serie A", 1490),
    (128, "128", "Liga Profesional Argentina", 1480),
    # --- Copas europeas ---
    (2, "2", "UEFA Champions League", 1600),
    (3, "3", "UEFA Europa League", 1500),
    (848, "848", "UEFA Europa Conference League", 1450),
    # --- Selecciones (todas las confederaciones) ---
    (1, "1", "World Cup", 1580),
    (4, "4", "Euro Championship", 1580),
    (31, "31", "World Cup Qualification CONCACAF", 1550),
    (32, "32", "World Cup Qualification Europe", 1550),
    (29, "29", "World Cup Qualification Africa", 1500),
    (30, "30", "World Cup Qualification Asia", 1500),
    (33, "33", "World Cup Qualification Oceania", 1450),
    (34, "34", "World Cup Qualification South America", 1560),
    (9, "9", "Copa America", 1560),
    (7, "7", "Asian Cup", 1500),
    (6, "6", "Africa Cup of Nations", 1500),
    (22, "22", "CONCACAF Gold Cup", 1500),
    (536, "536", "CONCACAF Nations League", 1500),
    (805, "805", "Copa Centroamericana", 1450),
    (10, "10", "Friendlies", 1500),
    # --- Norteamérica ---
    (253, "253", "MLS", 1450),
    (262, "262", "Liga MX", 1480),
    (479, "479", "Canadian Premier League", 1380),
    (257, "257", "US Open Cup", 1400),
    (259, "259", "Canadian Championship", 1380),
    # --- CONCACAF club cups ---
    (16, "16", "CONCACAF Champions Cup", 1450),
    (767, "767", "CONCACAF League", 1400),
    (1028, "1028", "CONCACAF Central American Cup", 1400),
    # --- Centroamérica doméstica ---
    (396, "396", "Nicaragua Primera Division", 1300),
    (162, "162", "Costa Rica Primera Division", 1350),
    (339, "339", "Guatemala Liga Nacional", 1300),
    (234, "234", "Honduras Liga Nacional", 1320),
    (370, "370", "El Salvador Primera Division", 1280),
    (304, "304", "Liga Panamena de Futbol", 1300),
    (416, "416", "Belize Premier League", 1250),
    # --- Inglaterra segunda división ---
    (40, "40", "Championship", 1300),
    
]

# Diccionario derivado para lookup por id_api.
API_FOOTBALL_LEAGUES_BY_ID = {
    lid: {"id": lid, "name": name, "initial_elo": elo}
    for lid, code, name, elo in API_FOOTBALL_LEAGUES
}

# Elo system constants (see docs/elo.md)
ELO_DEFAULT = 1500
ELO_HOME_ADVANTAGE = 80
ELO_K_DEFAULT = 20       # Clubes profesionales (ligas top)
ELO_K_INTERNATIONAL = 30  # Torneos internacionales (WC, WCQ, Euro, etc.)
ELO_K_MINOR = 25         # Ligas menores
ELO_K_NEW = 40           # Equipos nuevos (primeros partidos)
ELO_NEW_TEAM_MATCHES = 20
# IDs de competiciones internacionales (selecciones) que usan K mayor.
# Derivado del catálogo semilla; coincide con API-Football league IDs.
ELO_INTERNATIONAL_LEAGUE_IDS = frozenset({
    1,    # World Cup
    4,    # Euro Championship
    9,    # Copa America
    7,    # Asian Cup
    6,    # Africa Cup of Nations
    22,   # CONCACAF Gold Cup
    536,  # CONCACAF Nations League
    805,  # Copa Centroamericana
    31, 32, 29, 30, 33, 34,  # World Cup Qualification (todas las confederaciones)
    10,   # Friendlies (selecciones)
    2,    # UEFA Champions League
    3,    # UEFA Europa League
    848,  # UEFA Europa Conference League
    13,   # Copa Libertadores
    16,   # CONCACAF Champions Cup
})
# Umbral de Elo inicial del catálogo semilla para clasificar ligas menores.
# Competiciones con initial_elo < este valor usan K=25 en lugar de K=20.
ELO_MINOR_LEAGUE_THRESHOLD = 1400

# Forecast system constants (see docs/pronostico.md)
FORECAST_FORM_MATCHES = 5
FORECAST_MIN_HISTORY = 5
POISSON_MAX_GOALS = 5
# Corrección Dixon-Coles para baja anotación. rho negativo incrementa la
# probabilidad de 0-0 y 1-1 (Poisson independiente la subestima).
# Valor típico en fútbol: -0.13. 0.0 desactiva la corrección.
DIXON_COLES_RHO = -0.13
# Gol promedio histórico usado como base cuando un equipo no tiene
# historial suficiente (< FORECAST_MIN_HISTORY). El pronóstico fallback
# se basa solo en la diferencia Elo multiplicada por este baseline.
FORECAST_FALLBACK_BASELINE = 1.35
# Umbral de antigüedad (meses) para considerar la forma reciente de un
# equipo como "stale". Safety net alto (24m): con plan Pro no hay huecos
# irrecoverables, pero protege ante resincronizaciones o equipos
# inactivos largos.
FORECAST_STALE_MONTHS = 24

# Ventana de sincronización y pronóstico.
# Solo se pronostican y sincronizan partidos programados dentro de esta
# ventana hacia adelante (pronóstico semanal). Los datos lejanos cambian
# (fechas, forma reciente, Elo) por lo que no tiene sentido pronosticarlos.
FORECAST_SCHEDULE_DAYS = 7
# Ventana hacia atrás para capturar resultados recién finalizados
# (incluye aplazamientos/retardos de actualización de la API).
SYNC_BACK_DAYS = 3


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "alpha": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}