"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=".secret")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-+cu@_5o!b42y7pvtf(uwm+5b733946@#=on)3k(cd%j75tdd$z",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "teams",
    "matches",
    "elo",
    "forecasts",
    "stats",
    "api_client",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-ni"

TIME_ZONE = "America/Managua"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# API-Football (api-sports.io v3) — única fuente de datos.
#
# Competiciones de clubes, selecciones nacionales y amistosos. La
# cobertura se descubre dinámicamente vía /leagues (ver comando
# sync_competitions). API_FOOTBALL_LEAGUES es solo un catálogo semilla
# para calibrar el Elo inicial por liga; las ligas descubiertas que no
# estén listadas usan ELO_DEFAULT.
#
# Plan Free: 100 req/día, 10/min, solo temporadas 2022-2024, y date=
# restringido a hoy ± 1 día (ventana rolling de 3 días).
# Plan Pro: 7,500 req/día, 300/min, histórico profundo (~2008+) y
# temporada actual desbloqueada vía league+season y date= sin ventana.
# Los valores de rate-limit/budget están preparados para plan Pro.
API_CACHE_TTL_MINUTES = 60
API_FOOTBALL_KEY = os.environ.get("API_FOOTBALL_KEY", "")
API_FOOTBALL_BASE_URL = "https://v3.football.api-sports.io"
API_FOOTBALL_RATE_LIMIT_SECONDS = 0.25
API_FOOTBALL_DAILY_BUDGET = 7000

# Catálogo semilla de calibración Elo: (league_id, code, nombre, elo_inicial).
# code se almacena como Competition.code (el league_id como string).
# initial_elo se usa al crear LeagueStrength y al asignar Elo a equipos
# nuevos (ver docs/elo.md). Las ligas descubiertas no listadas aquí usan
# ELO_DEFAULT y se recalibran con recompute_league_strength tras el backfill.
API_FOOTBALL_LEAGUES = [
    # --- Ligas europeas top ---
    (39, "39", "Premier League", 1600, "LEAGUE", 80),
    (140, "140", "La Liga", 1570, "LEAGUE", 80),
    (78, "78", "Bundesliga", 1560, "LEAGUE", 80),
    (135, "135", "Serie A", 1550, "LEAGUE", 80),
    (61, "61", "Ligue 1", 1540, "LEAGUE", 80),
    (88, "88", "Eredivisie", 1450, "LEAGUE", 80),
    (94, "94", "Primeira Liga", 1450, "LEAGUE", 80),
    # --- Sudamérica ---
    (13, "13", "Copa Libertadores", 1500, "CONTINENTAL", 0),
    (11, "11", "Copa Sudamericana", 1450, "CONTINENTAL", 0),
    (71, "71", "Brasileirão Serie A", 1490, "LEAGUE", 80),
    (128, "128", "Liga Profesional Argentina", 1480, "LEAGUE", 80),
    # --- Copas europeas ---
    (2, "2", "UEFA Champions League", 1600, "CONTINENTAL", 0),
    (3, "3", "UEFA Europa League", 1500, "CONTINENTAL", 0),
    (848, "848", "UEFA Europa Conference League", 1450, "CONTINENTAL", 0),
    # --- Selecciones (todas las confederaciones) ---
    (1, "1", "World Cup", 1580, "WORLD_CUP", 0),
    (4, "4", "Euro Championship", 1580, "INTERNATIONAL", 0),
    (31, "31", "World Cup Qualification CONCACAF", 1550, "QUALIFIERS", 50),
    (32, "32", "World Cup Qualification Europe", 1550, "QUALIFIERS", 50),
    (29, "29", "World Cup Qualification Africa", 1500, "QUALIFIERS", 50),
    (30, "30", "World Cup Qualification Asia", 1500, "QUALIFIERS", 50),
    (33, "33", "World Cup Qualification Oceania", 1450, "QUALIFIERS", 50),
    (34, "34", "World Cup Qualification South America", 1560, "QUALIFIERS", 50),
    (9, "9", "Copa America", 1560, "INTERNATIONAL", 0),
    (7, "7", "Asian Cup", 1500, "INTERNATIONAL", 0),
    (6, "6", "Africa Cup of Nations", 1500, "INTERNATIONAL", 0),
    (22, "22", "CONCACAF Gold Cup", 1500, "INTERNATIONAL", 0),
    (536, "536", "CONCACAF Nations League", 1500, "INTERNATIONAL", 0),
    (805, "805", "Copa Centroamericana", 1450, "INTERNATIONAL", 0),
    (10, "10", "Friendlies", 1500, "FRIENDLY", 50),
    # --- Norteamérica ---
    (253, "253", "MLS", 1450, "LEAGUE", 80),
    (262, "262", "Liga MX", 1480, "LEAGUE", 80),
    (479, "479", "Canadian Premier League", 1380, "LEAGUE", 80),
    (257, "257", "US Open Cup", 1400, "CUP", 80),
    (259, "259", "Canadian Championship", 1380, "CUP", 80),
    # --- CONCACAF club cups ---
    (16, "16", "CONCACAF Champions Cup", 1450, "CONTINENTAL", 0),
    (767, "767", "CONCACAF League", 1400, "CONTINENTAL", 0),
    (1028, "1028", "CONCACAF Central American Cup", 1400, "CONTINENTAL", 0),
    # --- Centroamérica doméstica ---
    (396, "396", "Nicaragua Primera Division", 1300, "LEAGUE", 80),
    (162, "162", "Costa Rica Primera Division", 1350, "LEAGUE", 80),
    (339, "339", "Guatemala Liga Nacional", 1300, "LEAGUE", 80),
    (234, "234", "Honduras Liga Nacional", 1320, "LEAGUE", 80),
    (370, "370", "El Salvador Primera Division", 1280, "LEAGUE", 80),
    (304, "304", "Liga Panamena de Futbol", 1300, "LEAGUE", 80),
    (416, "416", "Belize Premier League", 1250, "LEAGUE", 80),
    # --- Inglaterra segunda división ---
    (40, "40", "Championship", 1300, "LEAGUE", 80),

]

# Diccionario derivado para lookup por id_api.
API_FOOTBALL_LEAGUES_BY_ID = {
    lid: {
        "id": lid,
        "name": name,
        "initial_elo": elo,
        "kind": kind,
        "home_advantage": hfa,
    }
    for lid, code, name, elo, kind, hfa in API_FOOTBALL_LEAGUES
}

# Elo system constants (see docs/elo.md)
ELO_DEFAULT = 1500
# Ventaja de localía por defecto (fallback cuando la competición no la
# define explícitamente). docs/elo.md: liga nacional 70-90, selecciones
# 50-80, Mundial/neutral 0. La localía real se toma de
# Competition.home_advantage; este valor solo se usa en cálculos
# manuales o si la competición no existe.
ELO_HOME_ADVANTAGE = 80
# Factor K por tipo de competición (docs/elo.md §Factor K).
#   Mundial 30, Eliminatorias 25, Primera división/Copas nacionales 20,
#   Amistosos 15. Equipos nuevos usan K=40 durante sus primeros
#   ELO_NEW_TEAM_MATCHES partidos, ignorando el kind.
ELO_K_DEFAULT = 20       # Clubes profesionales (ligas top)
ELO_K_WORLD_CUP = 30
ELO_K_QUALIFIERS = 25
ELO_K_CUP = 20
ELO_K_FRIENDLY = 15
ELO_K_CONTINENTAL = 25
ELO_K_NEW = 40
ELO_NEW_TEAM_MATCHES = 20

# Forecast system constants (see docs/pronostico.md, docs/xG.md)
# Forma reciente: dos ventanas (docs: Forma = 0.65·Forma20 + 0.35·Forma5).
FORECAST_FORM_SHORT = 5
FORECAST_FORM_LONG = 20
FORECAST_FORM_SHORT_WEIGHT = 0.35
FORECAST_FORM_LONG_WEIGHT = 0.65
# Ponderación temporal exp(-Dias/180) según docs/xG.md §Ponderación temporal.
FORECAST_DECAY_DAYS = 180
# Ataque/defensa separados por local/visitante: mínimo de partidos por
# condición para considerar el rating válido (si no, fallback Elo-only).
FORECAST_MIN_HISTORY = 5
FORECAST_MIN_VENUE_HISTORY = 3
# Clamp de goles esperados (docs/xG.md §Normalización): 0.20 ≤ λ ≤ 4.00.
FORECAST_LAMBDA_MIN = 0.20
FORECAST_LAMBDA_MAX = 4.00
# Factor Elo suave (no lineal). docs/xG.md §Corrección mediante Elo:
# "función suave que evite exagerar las diferencias". Usamos una tanh
# acotada: factor = 1 + gain·tanh(diff/scale). gain=0.5 limita el
# desplazamiento del λ a ±50% por Elo.
FORECAST_ELO_GAIN = 0.5
FORECAST_ELO_SCALE = 800.0
# Factor de forma multiplicativo sobre λ: ajuste leve (no dominante).
# docs/xG.md: "La forma complementa las estadísticas históricas, pero
# nunca las reemplaza." Limitamos el impacto a ±FORM_MAX_IMPACT.
FORECAST_FORM_MAX_IMPACT = 0.20
POISSON_MAX_GOALS = 5
# Corrección Dixon-Coles para baja anotación. rho negativo incrementa la
# probabilidad de 0-0 y 1-1 (Poisson independiente la subestima).
# Valor típico en fútbol: -0.13. 0.0 desactiva la corrección.
DIXON_COLES_RHO = -0.13
# Gol promedio histórico usado como base cuando un equipo no tiene
# historial suficiente (< FORECAST_MIN_HISTORY). El pronóstico fallback
# se basa solo en la diferencia Elo multiplicada por este baseline.
FORECAST_FALLBACK_BASELINE = 1.35
# Umbral de antigüedad (meses) para considerar la forma reciente de un
# equipo como "stale". Safety net alto (24m): con plan Pro no hay huecos
# irrecoverables, pero protege ante resincronizaciones o equipos
# inactivos largos.
FORECAST_STALE_MONTHS = 24

# Ventana de sincronización y pronóstico.
# Solo se pronostican y sincronizan partidos programados dentro de esta
# ventana hacia adelante (pronóstico semanal). Los datos lejanos cambian
# (fechas, forma reciente, Elo) por lo que no tiene sentido pronosticarlos.
FORECAST_SCHEDULE_DAYS = 7
# Ventana hacia atrás para capturar resultados recién finalizados
# (incluye aplazamientos/retardos de actualización de la API).
SYNC_BACK_DAYS = 3


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "alpha": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}