# Generated by Django 6.0.6 on 2026-06-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiResponseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("body", models.JSONField()),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caché API",
                "verbose_name_plural": "Cachés API",
                "indexes": [
                    models.Index(
                        fields=["fetched_at"], name="api_client__fetched_6d2e98_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BackfillJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("IN_PROGRESS", "En progreso"),
                            ("DONE", "Completado"),
                            ("EMPTY", "Sin partidos"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("fixtures_count", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, default="")),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backfill_jobs",
                        to="teams.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo de backfill",
                "verbose_name_plural": "Trabajos de backfill",
                "ordering": ["competition__id_api", "season"],
                "unique_together": {("competition", "season")},
            },
        ),
    ]
