# Generated by Django 6.0.6 on 2026-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiResponseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("body", models.JSONField()),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caché API",
                "verbose_name_plural": "Cachés API",
                "indexes": [
                    models.Index(
                        fields=["fetched_at"], name="api_client__fetched_6d2e98_idx"
                    )
                ],
            },
        ),
    ]
