# Generated by Django 6.0.6 on 2026-07-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xg_home", models.FloatField()),
                ("xg_away", models.FloatField()),
                ("prob_home_win", models.FloatField()),
                ("prob_draw", models.FloatField()),
                ("prob_away_win", models.FloatField()),
                ("prob_over_05", models.FloatField(default=0.0)),
                ("prob_over_15", models.FloatField(default=0.0)),
                ("prob_over_25", models.FloatField(default=0.0)),
                ("prob_over_35", models.FloatField(default=0.0)),
                ("prob_over_45", models.FloatField(default=0.0)),
                ("prob_btts", models.FloatField(default=0.0)),
                ("prob_btts_no", models.FloatField(default=0.0)),
                ("prob_score_home", models.FloatField(default=0.0)),
                ("prob_score_home_no", models.FloatField(default=0.0)),
                ("prob_score_away", models.FloatField(default=0.0)),
                ("prob_score_away_no", models.FloatField(default=0.0)),
                ("prob_1x", models.FloatField(default=0.0)),
                ("prob_x2", models.FloatField(default=0.0)),
                ("prob_12", models.FloatField(default=0.0)),
                ("prob_dnb_home", models.FloatField(default=0.0)),
                ("prob_dnb_away", models.FloatField(default=0.0)),
                ("top_score", models.CharField(blank=True, default="", max_length=10)),
                ("top_score_prob", models.FloatField(default=0.0)),
                ("form_home", models.JSONField(blank=True, default=dict)),
                ("form_away", models.JSONField(blank=True, default=dict)),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False,
                        help_text="True si se calculó solo con Elo (sin historial suficiente de forma reciente).",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronóstico",
                "verbose_name_plural": "Pronósticos",
                "ordering": ["-match__utc_date"],
            },
        ),
    ]
