# Generated by Django 6.0.6 on 2026-06-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xg_home", models.FloatField()),
                ("xg_away", models.FloatField()),
                ("prob_home_win", models.FloatField()),
                ("prob_draw", models.FloatField()),
                ("prob_away_win", models.FloatField()),
                ("form_home", models.JSONField(blank=True, default=dict)),
                ("form_away", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronóstico",
                "verbose_name_plural": "Pronósticos",
                "ordering": ["-match__utc_date"],
            },
        ),
    ]
