# Generated by Django 6.0.6 on 2026-06-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="prob_12",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_1x",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_btts",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_btts_no",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_dnb_away",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_dnb_home",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_over_05",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_over_15",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_over_25",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_over_35",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_over_45",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_x2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="top_score",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="forecast",
            name="top_score_prob",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="MarketForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("SHOTS", "Remates"),
                            ("SHOTS_ON_GOAL", "Remates al arco"),
                            ("CORNERS", "Córners"),
                            ("CARDS", "Tarjetas"),
                            ("FOULS", "Faltas"),
                            ("GOALS", "Goles"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lam", models.FloatField(default=0.0)),
                ("selection", models.CharField(max_length=40)),
                ("prob", models.FloatField(default=0.0)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("is_fallback", models.BooleanField(default=False)),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markets",
                        to="forecasts.forecast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mercado secundario",
                "verbose_name_plural": "Mercados secundarios",
                "ordering": ["market", "selection"],
                "unique_together": {("forecast", "market", "selection")},
            },
        ),
    ]
