# Generated by Django 6.0.6 on 2026-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="is_fallback",
            field=models.BooleanField(
                default=False,
                help_text="True si se calculó solo con Elo (sin historial suficiente de forma reciente).",
            ),
        ),
    ]
