# Generated by Django 6.0.6 on 2026-06-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "forecasts",
            "0002_forecast_prob_12_forecast_prob_1x_forecast_prob_btts_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="prob_score_away",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_score_away_no",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_score_home",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="forecast",
            name="prob_score_home_no",
            field=models.FloatField(default=0.0),
        ),
    ]
