# Generated by Django 6.0.6 on 2026-06-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EloLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo_before", models.FloatField()),
                ("elo_after", models.FloatField()),
                ("delta", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_logs",
                        to="matches.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elo_logs",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Elo",
                "verbose_name_plural": "Logs Elo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeagueStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.CharField(max_length=20)),
                ("average_elo", models.FloatField(default=1500.0)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strengths",
                        to="teams.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuerza de Liga",
                "verbose_name_plural": "Fuerza de Ligas",
                "unique_together": {("competition", "season")},
            },
        ),
    ]
